### ISSUE TITLE
EACS Fatal Error Cannot read from master config file

### ISSUE THREAD

**Issue by Kawalskint** [psidex/EACS#8]
Hi, looks like a very promising addon for Equalizer APO, but I cannot get it to work. I have followed the instructions to the letter and installed EACS on Windows 10 in the "APO install location>\EqualizerAPO\config" directory. When I start "EACS.exe" I receive a "EACS Fatal Error Cannot read from master config file" message. I have tried starting with admin privileges to see if that makes a difference, I have also uninstalled Equalizer APO and reinstalled from scratch, but does not solve the problem so far :-)

**Comment by psidex** [comment]
Hi, this is almost definitely happening because you have installed it in the wrong location. Make sure the `EACS.exe` file is located at `EqualizerAPO\config\EACS\EACS.exe`

(also try the new version I just released, [v0.4.1](https://github.com/psidex/EACS/releases/tag/v0.4.1))

Let me know if this works!

**Comment by Kawalskint** [comment]
Thanks, that fixed it.
